version: "3.7"
services:
    frontend:
        build: ./frontend
        image: frontend
        ports:
            - "5000:5000"
    backend:
        build: ./backend
        image: backend
        ports:
            - "8000:8000"
        environment:
            - REDIS=redis
    redis:
        image: redis
