version: "3.7"
services:
    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=example_user
            - POSTGRES_PASSWORD=example_password
            - POSTGRES_DB=example_db
        volumes:
            - ./database:/var/lib/postgresql/data
    frontend:
        build: ./frontend
        image: frontend
        environment:
            - API_URL=http://localhost/api
    backend:
        build: ./backend
        image: backend
        environment:
            - REDIS=redis
            - DB_USERNAME=example_user
            - DB_PASSWORD=example_password
            - DB_NAME=example_db
            - DB_HOST=db
        depends_on:
            - db
    redis:
        image: redis
        volumes:
            - ./redisdata:/data
    nginx:
        image: nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
          - "80:80"
        depends_on:
            - backend
            - frontend
